name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: true

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        # all supported versions are fetched from https://github.com/mamba-org/micromamba-releases/releases now and contain the build number
        micromamba-version: '1.2.0-1'

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: >
        micromamba create --name TEST python=${{ matrix.python-version }} pytest --file requirements-dev.txt --channel conda-forge
        && micromamba activate TEST

    - name: Install gliderad2cp
      shell: bash -l {0}
      run: >
        micromamba activate TEST
        && python -m pip install -e . --no-deps --force-reinstall


    - name: Tests
      shell: bash -l {0}
      run: >
        micromamba activate TEST
        && python -m pytest -rxs tests/
